let node_types={
    "1-1":{
        type_name:"机构",
        itemStyle:{
            normal:{
                color:"#3399FE"
            }
        },
        visible:true,
        symbolSize:50,
        category:0,
    },
    "1-2":{
        type_name:"人物", 
        itemStyle:{
            normal:{
                color:"#00009C"
            }
        },
        visible:true,
        symbolSize:28,
        category:1,
    },
    "1-2-1":{
        type_name:"人物虚拟集合", 
        itemStyle:{
            normal:{
                color:"#00009C"
            }
        },
        visible:false,
        symbolSize:38,
        category:1,
    },
    "1-3":{
        type_name:"产品", 
        itemStyle:{
            normal:{
                color:"#F10400"
            }
        },
        visible:true,
        symbolSize:28,
        category:2,
    },
    "1-3-1":{
        type_name:"产品集合", 
        itemStyle:{
            normal:{
                color:"#F10400"
            }
        },
        visible:false,
        symbolSize:38,
        category:2,
    },
    "1-4":{
        type_name:"业务", 
        itemStyle:{
            normal:{
                color:"#FF9E07"
            }
        },
        visible:true,
        symbolSize:28,
        category:3,
    },
    "1-4-1":{
        type_name:"业务集合", 
        itemStyle:{
            normal:{
                color:"#FF9E07"
            }
        },
        visible:false,
        symbolSize:28,
        category:3,
    },
    "1-5":{
        type_name:"文件", 
        itemStyle:{
            normal:{
                color:"#D9C761"
            }
        },
        visible:true,
        symbolSize:28,
        category:4,
    },
    "1-5-1":{
        type_name:"文件集合", 
        itemStyle:{
            normal:{
                color:"#D9C761"
            }
        },
        visible:false,
        symbolSize:38,
        category:4,
    },
    "2":{
        type_name:"指标", 
        itemStyle:{
            normal:{
                color:"#8D71C5"
            }
        },
        visible:true,
        symbolSize:28,
        category:5,
    },
    "2-1":{
        type_name:"指标集合", 
        itemStyle:{
            normal:{
                color:"#8D71C5"
            }
        },
        visible:false,
        symbolSize:38,
        category:5,
    },
    "3":{
        type_name:"属性", 
        itemStyle:{
            normal:{
                color:"#6B6B6B"
            }
        },
        visible:true,
        symbolSize:28,
        category:6,
    },
    "3-1":{
        type_name:"属性集合", 
        itemStyle:{
            normal:{
                color:"#6B6B6B"
            }
        },
        visible:false,
        symbolSize:38,
        category:6,
    },
    "4":{
        type_name:"关系", 
        itemStyle:{
            normal:{
                color:"#F69484"
            }
        },
        visible:true,
        symbolSize:28,
        category:7,
    },
    "4-1":{
        type_name:"关系集合", 
        itemStyle:{
            normal:{
                color:"#F69484"
            }
        },
        visible:false,
        symbolSize:38,
        category:7,
    },
    "5":{
        type_name:"事件", 
        itemStyle:{
            normal:{
                color:"#BA3284"
            }
        },
        visible:true,
        symbolSize:28,
        category:8,
    },
    "5-1":{
        type_name:"事件集合", 
        itemStyle:{
            normal:{
                color:"#BA3284"
            }
        },
        visible:false,
        symbolSize:38,
        category:8,
    }
}

export {node_types}